### ISSUE TITLE
Undefined variable in Figure 2 (?)

### ISSUE THREAD

**Issue by carlosdagos** [amiller/HoneyBadgerBFT#1]
Hi @amiller 

Reading the paper I noticed in Figure 2 (page 9) "wait to receive at least `t + 1` messages...", I believe this should be `f + 1`? Otherwise I'm a bit lost on what `t` means here.

Very good work. Thanks!

**Comment by amiller** [comment]
Right, this is supposed to be `f+1`

**Comment by carlosdagos** [comment]
Thanks :)

**Comment by sbellem** [comment]
This issue was moved to initc3/HoneyBadgerBFT-Python#5

**Comment by sbellem** [comment]
This issue was moved to initc3/HoneyBadgerBFT-Python#6
