### ISSUE TITLE
Common Coin : Why "source of random bits" is `PK.hash_message`, instead of the threshold signature?

### ISSUE THREAD

**Issue by dantengsky** [amiller/HoneyBadgerBFT#2]
According to the paper, common coin should 

> use the threshold signature as a source of random bits

but, it seems that the implementation (of shared_coin)

[amiller/HoneyBadgerBFT/blob/master/core/broadcasts.py#L105](https://github.com/amiller/HoneyBadgerBFT/blob/27d48d130bdd71ab363e3e06adddfbaa294d8f70/core/broadcasts.py#L105)

just abandon the (combined) signature, and use PK hash as source of randomness.

~~~
            if len(received[r]) == t + 1:
                    h = PK.hash_message(str((r, instance)))
                    def tmpFunc(r, t):
                        combine_and_verify(h, dict(tuple((t, deserialize1(sig)) for t, sig in received[r])[:t+1]))
                        outputQueue[r].put(ord(serialize(h)[0]) & 1)  # explicitly convert to int
                    Greenlet(
                        tmpFunc, r, t
                    ).start()
~~~

Is this a typo or am I missing something?

**Comment by amiller** [comment]
Hmm. That does look like some leftover "stub" code some how. Right now it seems like the `combine_and_verify` function in boldyreva_gipc.py only just returns `True` after forming the threshold signature, whereas it should return the actual threshold signature.

**Comment by dantengsky** [comment]
May I send a pull request?
