### ISSUE TITLE
[docs] Which style of docstrings to use?

### ISSUE THREAD

**Issue by sbellem** [amiller/HoneyBadgerBFT#20]
I would like to help in with the documentation of the code, and noticed different styles being used. 

In some places it's the normal standard docstrings, as in:

```python
def binaryagreement(sid, ...):
    '''Binary consensus ...

    :param sid: session identifier
    '''
```

while in other places it seems to be the [NumPy style](http://www.sphinx-doc.org/en/stable/ext/example_numpy.html#example-numpy) such as in:

```python
def reliablebroadcast(sid, pid, ...):
    """Reliable broadcast

    Args
    ----
    pid : 0 <= pid < N

    """
```

More generally, as far as I know there are three possible approaches:

* standard rst
* [google style](http://www.sphinx-doc.org/en/stable/ext/example_google.html#example-google)
* [numpy style](http://www.sphinx-doc.org/en/stable/ext/example_numpy.html#example-numpy)

The google and numpy styles are available via the [sphinx.ext.napoleon](http://www.sphinx-doc.org/en/stable/ext/napoleon.html) module.

Assuming that help is welcomed, then if a style is chosen I could help with setting up the documentation boilerplate, etc such that some documentation could be hosted on [readthedocs](https://readthedocs.org/) for instance, or wherever you wish.

**Comment by amiller** [comment]
Help is *most definitely* welcomed, thank you being here and what you've done so far!
Let's do standard docstrings as I don't have either "domain-specific" or "legacy" reasons to use something different.

**Comment by amiller** [comment]
I'm optimistically assuming you'll agree with this, and closing it as "decision made." Feel free to reopen if we need to consider anything else before choosing to adopt it. Maybe a separate issue will be needed to ensure existing documentation if useful is converted over.
