### ISSUE TITLE
[docs] Where to publish the docs?

### ISSUE THREAD

**Issue by sbellem** [amiller/HoneyBadgerBFT#26]
### Publishing on Read the Docs
It is very common for open source Python projects to host their documentation on [Read the Docs](https://readthedocs.org/).

It is usually relatively simple to set up. 

There are some limitations however in terms of what can be installed beyond Python packages specified in a `requirements.txt` file, and running `python setup.py install`. This means that for libraries that require installing C header files for instance, it does not seem to be possible to instruct Read the Docs to perform those required installations. In other words, it does not seem to be possible to instruct Read the Docs to execute:

```bash
apt-get -y install libgmp-dev libmpc-dev
wget https://crypto.stanford.edu/pbc/files/pbc-0.5.14.tar.gz
tar -xvf pbc-0.5.14.tar.gz
cd pbc-0.5.14 && ./configure && make && make install
git clone https://github.com/JHUISI/charm.git
cd charm && git checkout 2.7-dev && ./configure.sh && python setup.py install
```

Since the above instructions are required before running `python setup.py install` to install `honeybadgerbft`, and installing `honeybadgerbft` is required in order to build documentation from the the docstrings, it is then not simple to set up the docs on Read the Docs.

Perhaps there are workarounds, such as indicated [here](http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules), but this means it will take slightly longer to set up. 

### Publishing on Github Pages
Another approach would be to publish the docs on Github Pages. For a concrete example, one may look at the [asyncpg](https://github.com/MagicStack/asyncpg) project's [travis-publish-docs.sh](https://github.com/MagicStack/asyncpg/blob/master/.ci/travis-publish-docs.sh) script.

**Comment by amiller** [comment]
Let's defer this question of where to put it till resolving other issues, especially #20. For now, while the code is in transition into a complete library, I'm most concerned about coming up with a process that leads to good documentation following the code.

**Comment by sbellem** [comment]
This issue was moved to initc3/HoneyBadgerBFT-Python#30
