### ISSUE TITLE
Improvements to conference paper

### ISSUE THREAD

**Issue by sbellem** [amiller/HoneyBadgerBFT#31]
The purpose of this issue is to communicate small improvements (such as typos) to the research paper by Miller et al. [The Honey Badger of BFT Protocols](https://eprint.iacr.org/2016/199).

**Comment by sbellem** [comment]
_small typos_

> ### 4.4 Instantiating ACS Efficiently

(*page 7, last paragraph before subsubsection* **Communication-optimal reliable broadcast**)

> We now briefly explain the RBC and ABA constructions before explaing the Ben-Or protocol in more detail.

"explaing" --> "explaining"

> #### Communication-optimal reliable broadcast
(*page 7, last paragraph of subsubsection* **Communication-optimal reliable broadcast**)

> If the sender is correct, the total running time is three (asynchronous) rounds; and in any case, at most two rounds elapse between when the first correct node outputs a value and the last outputs a value. The reliable broadcast algorithm shown in Figure 2.

"is" seems to be missing

> The reliable broadcast algorithm **is** shown in Figure 2.

**Comment by sbellem** [comment]
_wondering ..._

> ### 1.1 Our Contributions
> #### Timing assumptions considered harmful.
> [...]

_on page 2, first paragraph_

>   Second, even when the weak synchrony assumptions are satisfied in practice, weakly synchronous protocols degrade significantly in throughput when the underlying network is unpredictable. Ideally, we would like a protocol whose throughput closely tracks the network’s performance even under rapidly changing network conditions. Unfortunately, **weakly asynchronous** protocols require timeout parameters that are finicky to tune, especially in cryptocurrency application settings; and when the chosen timeout values are either too long or too short, throughput can be hampered. As a concrete example, we show that even when the weak synchrony assumptions are satisfied, such protocols are slow to recover from transient network partitions (Section 3).

"weakly **a**synchronous" --> "weakly synchronous" (?)

**Comment by sbellem** [comment]
_wondering ..._

> ## C. ASYNCHRONOUS BINARY BYZANTINE AGREEMENT
>
> #### Realizing binary agreement from a common coin.
> [...]
> We instantiate this primitive with a protocol based on cryptographic common coin, which essentially act as synchronizing gadgets.

"on cryptographic common coin" --> "on cryptographic common coin**s**" (?)

**Comment by sbellem** [comment]
> ## 7. Reference

ref [42]:

>    A. Mostefaoui, H. Moumen, and M. Raynal. Signature-free asynchronous byzantine consensus with t< n/3 and o (n 2) messages. In Proceedings of the 2014 ACM symposium on Principles of distributed computing, pages 2–9. ACM, 2014.

o (n 2) --> O (n^2)

**Comment by amiller** [comment]
In Figure 11,  `bin_vals_r` instead of `vals`

**Comment by sbellem** [comment]
> ## 3. THE GAP BETWEEN ASYNCHRONOUS AND  WEAKLY  SYNCHRONOUS  NETWORK MODELS
> 
> In this section, we **present make** two counter arguments that refute the premise above. 

present _or_ make ?

**Comment by sbellem** [comment]
_page 2, left column, bottom_

> We provide a full-fledged implementation of HoneyBadgerBFT, which **will we** release as free open source software in the near future.

will we --> we will

**Comment by sbellem** [comment]
> ## DEFERRED PROOFS
> [...]
> 
> **Experiment 1.** [...] The adversary selects `N - 2f` correct nodes and let `S` denote the union of their proposed transactions -- recall that the ACS protocol guarantees that the agreed set **contains at least transactions** proposed by `N - 2f` correct nodes.

contains at least transactions --> contains at least `B/4` transactions (?)

> **Experiment 2.** [...]
> [...]
> [...] If the average number of transactions across these epochs is smaller than `1/4 * B`, `D` guesses that the ciphertexts are real; otherwise it **guess** they are random.

guess --> guesses (?)

**Comment by sbellem** [comment]
> **Applicability to permissionless blockchains.**
[...]
Several recent works have suggested the promising idea of leveraging either a slower, external blockchain such as Bitcoin or economic “proof-of-stake” assumptions involving the underlying currency itself [32, **32**, 35, 37] to bootstrap faster BFT protocols, by selecting a random committee to perform BFT in every different epoch. 

[32, 32, 35, 37] --> [32, 35, 37] ?

**Comment by sbellem** [comment]
> ### 5.1 Bandwidth Breakdown and Evaluation
> ...
> **Bandwidth and breakdown findings.** ...
> ...
> The system’s effective throughput ... However, **when when** the batch size reaches 16384, ...

when when --> when

**Comment by sbellem** [comment]
This issue was moved to initc3/HoneyBadgerBFT-Python#36
