### ISSUE TITLE
[packaging] Register package on PyPI

### ISSUE THREAD

**Issue by sbellem** [amiller/HoneyBadgerBFT#32]
I doubt this would happen but just to avoid the complications of someone else registering a package with the same name, say "honeybadger big file transfers --> honeybadgerbft",  it may be a good idea to register the package on PyPI, to reserve the package name `honeybadgerbft`. 

No need to upload code.

I can take care of this, but will nevertheless provide links to relevant documentation in upcoming days.

In the mean time here's a sample of what this could look like (please note that this is on the **test server** of PyPI): https://testpypi.python.org/pypi/honeybadgerbft/0.1.0

The package owner can be changed, so once you are setup on PyPI, we could make the change.

**Comment by amiller** [comment]
I'm `amiller` on pypi

**Comment by sbellem** [comment]
Created a dedicated branch for the planning release: https://github.com/sbellem/HoneyBadgerBFT/tree/planning-release-for-pypi

The diff is here: https://github.com/amiller/HoneyBadgerBFT/compare/dev...sbellem:planning-release-for-pypi

The steps to make the release are as follows:

```bash
$ pip install twine
$ python setup.py sdist
$ gpg --detach-sign -a dist/honeybadgerbft-0.0.0.tar.gz
$ twine upload --repository <pypirc-section> --config-file <pypirc-file-full-path> dist/honeybadgerbft-0.0.4.tar.gz dist/honeybadgerbft-0.0.4.tar.gz.asc
```
docs are at https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

So if you prefer to do the upload you can follow the above and if you need help please ask me.

Otherwise I'll wait for your signal to do the upload and will make the ownership change to `amiller`.

**Comment by sbellem** [comment]
Planning release is up: https://pypi.python.org/pypi/honeybadgerbft/0.0.0
