### ISSUE TITLE
Implement proposed batch size to be floor(B/N)

### ISSUE THREAD

**Issue by sbellem** [amiller/HoneyBadgerBFT#36]
@amiller  I assume you are well aware of this as there's already a `TODO` note in the code about implementing the random selection.

Nevertheless, regardless of the size, only one element (`tx_to_send[0]`) is currently passed to [`_run_round()`](https://github.com/amiller/HoneyBadgerBFT/blob/dev/honeybadgerbft/core/honeybadger.py#L74):

```python
class HoneyBadgerBFT():
    # ...
    def run(self):
        # ...
        while True:
            # ...
            # Select all the transactions (TODO: actual random selection)
            tx_to_send = self.transaction_buffer[:self.B]

            # Run the round
            send_r = _make_send(r)
            recv_r = self._per_round_recv[r].get
            new_tx = self._run_round(r, tx_to_send[0], send_r, recv_r)
```

So `_run_round()` and `tpke.encrypt()` should be capable to take a `list` or a similar data structure.

`tpke.encrypt()` would need to be modified so that a string (e.g.: `cPickle.dumps(raw)`) is passed to the padding operation.

So this issue could be done in two (or three) parts:

1. Pass a list to `_run_round()`, e.g.: `tx_to_send[:1]`
2. Pass `floor(B/N)` transactions to `_run_round()`, e.g.: `tx_to_send[:int(B/N)]`
3. Implement the random selection

**Comment by amiller** [comment]
We're already doing a version of this in the `demo3` branch but it was made in kind of a rush https://github.com/amiller/HoneyBadgerBFT/commit/6c3f710dfb561d2c27f28b955450ad020691c4ba

**Comment by sbellem** [comment]
> We're already doing a version of this in the demo3 branch but it was made in kind of a rush 6c3f710

Ah ok, cool! I had not looked at other branches!

Feel free to close or leave open, or transform the goal of the issue into incorporating 6c3f710 into dev ...

**Comment by afck** [comment]
I'd maybe use `max(1, floor(B / N))`, just so that it also works in use cases with very small batch sizes where `B / N` would be 0.

**Comment by sbellem** [comment]
This issue was moved to initc3/HoneyBadgerBFT-Python#28

\cc @afck
