### ISSUE TITLE
[dev] update/fix experiments

### ISSUE THREAD

**Issue by sbellem** [amiller/HoneyBadgerBFT#45]
The experiments need to be updated to match the changes made in the `dev` branch.

**NOTE**: There's a work-in-progress branch addressing this issue: https://github.com/sbellem/HoneyBadgerBFT/tree/experiments

**Comment by amiller** [comment]
The experiments might be outdated in design. They're useful for measuring bandwidth usage and other resource costs. To get the high scores we reported in the paper, we used a manually-optimized/compressed encoding format, but tossed it out during refactoring for simplicity. The most realistic experiment is the distributed EC2 experiment. It would be better to run some kind of "docker compose" based local network experiment.

**Comment by sbellem** [comment]
> It would be better to run some kind of "docker compose" based local network experiment.

Ah yeah, cool! I could help with that!

**Comment by sbellem** [comment]
This issue was moved to initc3/HoneyBadgerBFT-Python#23
