### ISSUE TITLE
Issue running an instance with Docker

### ISSUE THREAD

**Issue by mohamedGr** [amiller/HoneyBadgerBFT#62]
Hi,
I have successfully built the docker image but when I try to execute the following docker command:
`docker run -e N="8" -e t="2" -e B="16" -it honeybadgerbft
`
I get the following error

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/HoneyBadgerBFT/test/honest_party_test.py", line 4, in <module>
>     monkey.patch_all()
>   File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 889, in patch_all
>     _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
>   File "/usr/local/lib/python2.7/dist-packages/gevent/monkey.py", line 167, in _notify_patch
>     notify_and_call_entry_points(event)
>   File "/usr/local/lib/python2.7/dist-packages/gevent/events.py", line 112, in notify_and_call_entry_points
>     subscriber = plugin.load()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2317, in load
>     self.require(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2340, in require
>     items = working_set.resolve(reqs, env, installer, extras=self.extras)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 779, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (greenlet 0.4.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('greenlet>=0.4.13'))

I am running ubuntu 16.04. Any suggestions on how to solve this issue?

Thanks a lot for your help

**Comment by mohamedGr** [comment]
Thanks for the fix!
  
Now when I run the same command, I get this error:

> timestampB (2, 1528223774.181704)
[2] proposing 2 transactions
timestampIB (2, 1528223774.191895)
timestampB (3, 1528223774.192231)
[3] proposing 2 transactions
timestampIB (3, 1528223774.200394)
timestampB (6, 1528223774.200659)
[6] proposing 2 transactions
timestampIB (6, 1528223774.208435)
timestampB (7, 1528223774.208616)
[7] proposing 2 transactions
timestampIB (7, 1528223774.217415)
timestampB (0, 1528223774.218628)
[0] proposing 2 transactions
timestampIB (0, 1528223774.228907)
timestampB (5, 1528223774.229763)
[5] proposing 2 transactions
timestampIB (5, 1528223774.238472)
timestampB (4, 1528223774.238788)
[4] proposing 2 transactions
timestampIB (4, 1528223774.246989)
timestampB (1, 1528223774.247289)
[1] proposing 2 transactions
timestampIB (1, 1528223774.256407)
timestampIE (0, 1528223776.070820)
timestampIE2 (0, 1528223776.087000)
timestampIE (1, 1528223776.088184)
timestampIE2 (1, 1528223776.106821)
timestampIE (2, 1528223776.108900)
timestampIE2 (2, 1528223776.131261)
timestampIE (3, 1528223776.131447)
timestampIE2 (3, 1528223776.148224)
timestampIE (4, 1528223776.304321)
timestampIE2 (4, 1528223776.350086)
timestampIE (5, 1528223776.353822)
timestampIE2 (5, 1528223776.399959)
timestampE (0, 1528223776.403650)
[0] 10 distinct tx synced and 6 tx left in the pool.
timestampE (1, 1528223776.403747)
[1] 10 distinct tx synced and 6 tx left in the pool.
timestampE (2, 1528223776.403900)
[2] 10 distinct tx synced and 6 tx left in the pool.
timestampE (3, 1528223776.403996)
[3] 10 distinct tx synced and 6 tx left in the pool.
timestampIE (6, 1528223776.404808)
timestampIE2 (6, 1528223776.451505)
timestampE (4, 1528223776.478532)
[4] 10 distinct tx synced and 6 tx left in the pool.
timestampIE (7, 1528223776.481560)
timestampIE2 (7, 1528223776.537092)
timestampE (5, 1528223776.543487)
[5] 10 distinct tx synced and 6 tx left in the pool.
Concensus Finished
Entering atexit()
msgCounter 9024
msgTypeCounter [[0, 0], [64, 24566], [512, 197112], [2560, 25600], [2496, 24960], [2432, 94848], [512, 20480], [384, 28032]]
    Init      Echo      Val       Aux      Coin     Ready    Share
      64      512      2560      2496      2432       512       384
   24566   197112     25600     24960     94848     20480     28032
Total Message size 390959
timestampE (6, 1528223776.568858)
[6] 10 distinct tx synced and 6 tx left in the pool.
Exception KeyError: KeyError(139677818926896,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored
Process _GProcess-1:

After googling this issue, it seems it's related to monkey-patching the threading module.

Thank you!

**Comment by sbellem** [comment]
Thanks for your feedback @mohamedGr 

This will be fixed as soon as possible (see related issue #45).

**Comment by fuji0510** [comment]
How built the docker image ? @mohamedGr

**Comment by sbellem** [comment]
> How built the docker image ? @mohamedGr

until PR #62 is merged, you can checkout the code of the PR and run:

```bash
docker build --no-cache docker/
```

to check the code of the PR:

```bash
git fetch <remote_name> pull/62/head:BRANCHNAME
git checkout BRANCHNAME
```

`<remote_name>` should point to the repo (amiller/HoneyBadgerBFT -- ssh or https)

see https://help.github.com/articles/checking-out-pull-requests-locally/ for more information
